#!/usr/bin/php -q
<?php
define('IN_SCRIPT',true);

if(!defined("STDIN")){
   define("STDIN", fopen('php://stdin','r'));
}

include("includes/class.core.php");

$Core = new Core();

$d = $Core::$Sql->prepare("SELECT * FROM `account` WHERE `email` = 'admin@isengard.dk'");
$d->execute();
$d = $d->fetch();

$Core->Users->userLogin('admin@isengard.dk','bjo10ern21');

if($d['username']){
  echo "Yo ".$d['username']."\r\n";
}

echo "Please enter your username:\n";
$strName = fread(STDIN, 80); // Read up to 80 characters or a newline
echo "Please enter your password:\n";
$strPass = fread(STDIN, 80);

$Core::$Users->userLogin($strName,$strPass);

/*
if(exec() == "Nickless"){ 
  echo "Hi ".$q; 
}*/
?>
