#!/usr/bin/php -q
<?php
define('IN_SCRIPT',true);

if(!defined("STDIN")){
   define("STDIN", fopen('php://stdin','r'));
}

include("includes/class.core.php");

$Core = new Core();

$d = $Core::$Sql->prepare("SELECT * FROM `account` WHERE `email` = 'admin@isengard.dk'");
$d->execute();
$d = $d->fetch();

if($d['username']){
  echo "Yo ".$d['username']."\r\n";
}

if(!$Core::$Users->isLogged()){
  $Core::$Users->userLogin('admin@isengard.dk','bjo10ern21');
}else{
  echo "is logged";
}

?>
